name: Flutter CI

# මම push කරන හැම වෙලේම මේක run වෙන්න ඕනේ
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Check for errors (Analyze)
      run: flutter analyze

    - name: Run Build Test
      run: flutter build apk --debug