// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9JN_BBMr03zPnCh4XpjQ2V6F7tIPYQg',
    appId: '1:910011999028:web:c4693792fcea2de738fb61',
    messagingSenderId: '910011999028',
    projectId: 'suhada-inventory',
    authDomain: 'suhada-inventory.firebaseapp.com',
    storageBucket: 'suhada-inventory.firebasestorage.app',
    measurementId: 'G-F3K7E7E7DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgIkKkT8Pa8HHkIfbc8adz2vCF7IqoVII',
    appId: '1:910011999028:android:1a6021dd891c75fe38fb61',
    messagingSenderId: '910011999028',
    projectId: 'suhada-inventory',
    storageBucket: 'suhada-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PeRKCoustDtdAI-adPpMS64CXmOGURQ',
    appId: '1:910011999028:ios:c70fec5e193e42a938fb61',
    messagingSenderId: '910011999028',
    projectId: 'suhada-inventory',
    storageBucket: 'suhada-inventory.firebasestorage.app',
    iosBundleId: 'com.example.stocksuhada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2PeRKCoustDtdAI-adPpMS64CXmOGURQ',
    appId: '1:910011999028:ios:c70fec5e193e42a938fb61',
    messagingSenderId: '910011999028',
    projectId: 'suhada-inventory',
    storageBucket: 'suhada-inventory.firebasestorage.app',
    iosBundleId: 'com.example.stocksuhada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9JN_BBMr03zPnCh4XpjQ2V6F7tIPYQg',
    appId: '1:910011999028:web:40bd396de002261638fb61',
    messagingSenderId: '910011999028',
    projectId: 'suhada-inventory',
    authDomain: 'suhada-inventory.firebaseapp.com',
    storageBucket: 'suhada-inventory.firebasestorage.app',
    measurementId: 'G-GVW82ZETZ4',
  );
}
